### ISSUE TITLE
函数可变参数导出报错

### ISSUE THREAD

**Issue by baljj** [yanghuan/CSharp.lua#277]
**报错代码**：
   m_avatar.HandleEvent(EAvatarEvent.evtAttachEffect, ske, effect, localPosition, localRotation);

**HandleEvent 函数定义**：
public void HandleEvent(EAvatarEvent evt, params object[] args)

**错误以及堆栈提示**：
CSharpLua.BugErrorException: SourceLocation(L:/Unity/CSharpToLua/CSharpLuaForUnity-master/Assets/CSharpLua/Compiled\Main\GameObject\XGameObject.cs@631:9)"if (m_avatar != null) m_avatar.HandleEvent(EAvatarEvent.evtAttachEffect, ske, effect, localPosition, localRotation);": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue

 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)

   at CSharpLua.LuaSyntaxNodeTransform.GetParameterSymbol(IMethodSymbol symbol, ArgumentSyntax argument) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1059

   at CSharpLua.LuaSyntaxNodeTransform.CheckValueTypeClone(ITypeSymbol typeSymbol, IdentifierNameSyntax node, LuaExpressionSyntax& expression, Boolean isPropertyField) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1102

   at CSharpLua.LuaSyntaxNodeTransform.VisitIdentifierName(IdentifierNameSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3083

   at Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)

   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1284

   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1288

   at CSharpLua.LuaSyntaxNodeTransform.FillInvocationArgument(List`1 arguments, ArgumentSyntax node, ImmutableArray`1 parameters, List`1 refOrOutArguments) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3149

**Comment by yanghuan** [comment]
```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Test {
  public class A {
    public void HandleEvent(int evt, params object[] args) {

    }
  }

  class Program {
    public static void Main(string[] args) {
      int ske, effect, localPosition, localRotation;
      ske = 0;
      effect = 0;
      localPosition = 0;
      localRotation = 0;
      A a = new A();
      a.HandleEvent(2, ske, effect, localPosition, localRotation);
    }
  }
}
```
使用此代码测试未发现问题，看堆栈出错的代码行号也和目前最新代码不匹配。
可使用目前最新代码验证下。

**Comment by baljj** [comment]
**FlyStringHalf  函数中的 HandleEvent 没有报错**
	public void FlyStringHalf(EObjectHalfHintType ht, string str)
	{
		if (null == m_avatar) return ;
		m_avatar.**HandleEvent** (EAvatarEvent.evtFlyStringHalf, ht, str);
	}
	 **AttachEffect函数 中的HandleEvent 报错**
    public void AttachEffect(ESkeleton ske, XU3dEffect effect, Vector3 localPosition, Vector3 localRotation)
    {
        if (null == effect) return;
        if (m_avatar != null) m_avatar.**HandleEvent**(EAvatarEvent.evtAttachEffect, ske, effect, localPosition, localRotation);
    }	

使用了最新的代码还是出现改问题，最新报错堆栈如下：
CSharpLua.BugErrorException: SourceLocation(L:/Unity/CSharpToLua/CSharpLuaForUnity-master/Assets/CSharpLua/Compiled\Main\GameObject\XGameObject.cs@631:9)"if (m_avatar != null) m_avatar.HandleEvent(EAvatarEvent.evtAttachEffect, ske, effect, localPosition, localRotation);": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue

 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.

   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)

   at CSharpLua.LuaSyntaxNodeTransform.GetParameterSymbol(IMethodSymbol symbol, ArgumentSyntax argument) in G:\Working\Unity\CSharp.lua-master\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1073

   at CSharpLua.LuaSyntaxNodeTransform.CheckValueTypeClone(ITypeSymbol typeSymbol, IdentifierNameSyntax node, LuaExpressionSyntax& expression, Boolean isPropertyField) in G:\Working\Unity\CSharp.lua-master\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1116

   at CSharpLua.LuaSyntaxNodeTransform.VisitIdentifierName(IdentifierNameSyntax node) in G:\Working\Unity\CSharp.lua-master\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3088

   at Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)

   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in G:\Working\Unity\CSharp.lua-master\CSharp.lua\Utils.cs:line 1284

   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in G:\Working\Unity\CSharp.lua-master\CSharp.lua\Utils.cs:line 1288

**Comment by baljj** [comment]
测试发现只是有几处调用会出现上述问题，具体原因不知，修改实现方式跳过这个问题了

**Comment by yanghuan** [comment]
参数有结构体类型才会有这个问题

**Comment by baljj** [comment]
好的， 谢谢
