### ISSUE TITLE
编译时候报错

### ISSUE THREAD

**Issue by yingnierxiao** [yanghuan/CSharp.lua#298]
CompiledFail: Compile fail, System.NullReferenceException: Object reference not set to an instance of an object.
   at CSharpLua.LuaSyntaxGenerator.PretreatmentChecker.CheckImplicitInterfaceImplementation(INamedTypeSymbol type) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 1331
   at CSharpLua.LuaSyntaxGenerator.PretreatmentChecker.Check() in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 1320
   at CSharpLua.LuaSyntaxGenerator.PretreatmentChecker..ctor(LuaSyntaxGenerator generator) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 1284
   at CSharpLua.LuaSyntaxGenerator.DoPretreatment() in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 1429
   at CSharpLua.LuaSyntaxGenerator..ctor(IEnumerable`1 codes, IEnumerable`1 libs, IEnumerable`1 cscArguments, IEnumerable`1 metas, SettingInfo setting) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 188
   at CSharpLua.Compiler.GetGenerator() in D:\Project\Person\CSharp.lua\CSharp.lua\Compiler.cs:line 153
   at CSharpLua.Compiler.Compile() in D:\Project\Person\CSharp.lua\CSharp.lua\Compiler.cs:line 121
   at CSharpLua.Program.Main(String[] args) in D:\Project\Person\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 84

**Comment by yanghuan** [comment]
我看了下代码行号已经发生变化，可以使用最新的代码在测试下
