### ISSUE TITLE
Try Live functionality broken

### ISSUE THREAD

**Issue by petterannerwall** [yanghuan/CSharp.lua#326]
Hey there, was checking this out and when I went to the Try Live functionality and there seems to be something missing on the server side. I get the error below in the LUA window on this link: https://yanghuan.github.io/external/bridgelua-editor/index.html

```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/snap/dotnet-sdk/93/shared/Microsoft.NETCore.App/5.0.0-preview.7.20364.11'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at CSharpLua.Compiler.GetSystemLibs() in D:\Project\Person\CSharp.lua\CSharp.lua\Compiler.cs:line 80
   at CSharpLua.Compiler.CompileSingleCode(String code) in D:\Project\Person\CSharp.lua\CSharp.lua\Compiler.cs:line 159
   at CSharpLuaWeb.Program.Compile(String code) in D:\Project\Person\CSharpLuaWeb\CSharpLuaWeb\Program.cs:line 26
```

**Comment by yanghuan** [comment]
thankds report, i fix already
