### ISSUE TITLE
Bug when compiling Google Protobuf v3.17.3

### ISSUE THREAD

**Issue by RegisFrey** [yanghuan/CSharp.lua#367]
Attempting to compile https://github.com/protocolbuffers/protobuf/tree/v3.17.3/csharp/src/Google.Protobuf

NOTE: had to add unsafe flag to compile this version due to `Source/Packages/Protobuf/WritingPrimitives.cs(73,35): error CS0227: Unsafe code may only appear if compiling with /unsafe`

So the build command used was `dotnet ./CSharpLua/CSharp.lua/CSharp.Lua.Launcher.dll -csc -unsafe -s Source/Packages/Protobuf -d Compiled/Packages/Protobuf `

MacOS 11.2.3
dotnet 5.0.204
CSharpLua 1.7

CSharpLua is reporting failure at https://github.com/protocolbuffers/protobuf/blob/v3.17.3/csharp/src/Google.Protobuf/WritingPrimitives.cs#L220

```
CSharpLua.BugErrorException: SourceLocation(Source/Packages/Protobuf/WritingPrimitives.cs@220:13)"ref char sourceChars = ref MemoryMarshal.GetReference(value.AsSpan());": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CSharpLua.LuaSyntaxNodeTransform.AddRefInvocationVariableMapping(InvocationExpressionSyntax expression, LuaInvocationExpressionSyntax invocation, VariableDeclaratorSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 2187
   at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclaration(VariableDeclarationSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3393
   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1320
   at CSharpLua.LuaSyntaxNodeTransform.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3343
   at Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1333
   --- End of inner exception stack trace ---
   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 219
   at CSharpLua.LuaSyntaxGenerator.Generate(String outFolder) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 246
   at CSharpLua.Compiler.Compile() in D:\Project\Person\CSharp.lua\CSharp.lua\Compiler.cs:line 123
   at CSharpLua.Program.Main(String[] args) in D:\Project\Person\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 90
```

**Comment by RegisFrey** [comment]
I think this is my last issue from my experiments today.

Thank you for making this tool, it was cool to have any ability at all to try cross compiling C# into Lua. I had fun poking around and getting some stuff to come across.

I don't want these issues to create any stress.
I'm just sharing these issues ( https://github.com/yanghuan/CSharp.lua/issues/364 https://github.com/yanghuan/CSharp.lua/issues/365 https://github.com/yanghuan/CSharp.lua/issues/366 https://github.com/yanghuan/CSharp.lua/issues/367 ) in case they are helpful. I don't need fixes.
This was just a fun experiment to see if I could. There's also a good chance I'm doing something dumb, so apologies if that's the case.

Thanks again! 
Have a great day.
