### ISSUE TITLE
无法翻译强制转换方法

### ISSUE THREAD

**Issue by a772616239** [yanghuan/CSharp.lua#369]
public static implicit operator float3(FixVector3 value)
    {
        return new float3(value.x, value.y , value.z );
    }

**Comment by a772616239** [comment]
DCETEditor.LuaCompiler+CompiledFail: Compile fail, CSharpLua.BugErrorException: SourceLocation(./Assets/Components\Fix64.cs@530:9)"return new float3(value.x, value.y , value.z );": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
 ---> System.Diagnostics.Contracts.ContractException
 ---> System.ApplicationException
   at CSharpLua.LuaSyntaxGenerator.<>c.<.cctor>b__29_0(Object _, ContractFailedEventArgs e) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 139
   at System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   at System.Diagnostics.Contracts.Contract.ReportFailure(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   at System.Diagnostics.Contracts.Contract.Assert(Boolean condition)
   at CSharpLua.LuaSyntaxNodeTransform.GetConstructorIndex(IMethodSymbol symbol) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1819
   at CSharpLua.LuaSyntaxNodeTransform.BuildObjectCreationInvocation(IMethodSymbol symbol, LuaExpressionSyntax expression) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1040
   at CSharpLua.LuaSyntaxNodeTransform.GetObjectCreationExpression(IMethodSymbol symbol, BaseObjectCreationExpressionSyntax node) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 34
   at CSharpLua.LuaSyntaxNodeTransform.VisitObjectCreationExpression(ObjectCreationExpressionSyntax node) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 85
   at Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\Utils.cs:line 1385
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\Utils.cs:line 1389
   at CSharpLua.LuaSyntaxNodeTransform.VisitExpression(ExpressionSyntax node) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1322
   at CSharpLua.LuaSyntaxNodeTransform.VisitReturnStatement(ReturnStatementSyntax node) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1514
   at Microsoft.CodeAnalysis.CSharp.Syntax.ReturnStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1327
   --- End of inner exception stack trace ---
   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 227
   at CSharpLua.LuaSyntaxGenerator.Generate(String outFolder) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 254
   at CSharpLua.Compiler.Compile() in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua\Compiler.cs:line 124
   at CSharpLua.Program.Main(String[] args) in C:\Users\Administrator\Documents\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 90


dotnet ./Tools/CSharpLua/net5.0/CSharp.lua.Launcher.dll  -s "./Assets/Components" -d "E:/MainPro1/Unity/Assets/Res/Lua/Core" -l "C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\Unity.Cecil.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\Unity.Cecil.Mdb.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\Unity.Cecil.Pdb.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.CoreModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.DeviceSimulatorModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.GraphViewModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.PackageManagerUIModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.QuickSearchModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.SceneTemplateModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.UIBuilderModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.UIElementsModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.UIElementsSamplesModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.UIServiceModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEditor.UnityConnectModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.AccessibilityModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.AIModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.AndroidJNIModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.AnimationModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.ARModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.AssetBundleModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.AudioModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.ClothModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.ClusterInputModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.ClusterRendererModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.CoreModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.CrashReportingModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.DirectorModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.DSPGraphModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.GameCenterModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.GIModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.GridModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.HotReloadModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.ImageConversionModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.IMGUIModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.InputLegacyModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.InputModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.JSONSerializeModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.LocalizationModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.ParticleSystemModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.PerformanceReportingModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.Physics2DModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.PhysicsModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.ProfilerModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.ScreenCaptureModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.SharedInternalsModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.SpriteMaskModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.SpriteShapeModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.StreamingModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.SubstanceModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.SubsystemsModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.TerrainModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.TerrainPhysicsModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.TextCoreModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.TextRenderingModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.TilemapModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.TLSModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UIElementsModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UIElementsNativeModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UIModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UmbraModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UNETModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityAnalyticsModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityConnectModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityCurlModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityTestProtocolModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityWebRequestAssetBundleModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityWebRequestAudioModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityWebRequestModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityWebRequestTextureModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.UnityWebRequestWWWModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.VehiclesModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.VFXModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.VideoModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.VirtualTexturingModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.VRModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.WindModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\Managed\UnityEngine\UnityEngine.XRModule.dll;C:\Program Files\Unity\Hub\Editor\2021.1.18f1c1\Editor\Data\MonoBleedingEdge\lib\mono\unityjit\Facades\netstandard.dll;E:\MainPro1\Unity\Library\ScriptAssemblies\Unity.Entities.dll!;E:\MainPro1\Unity\Library\ScriptAssemblies\Unity.Mathematics.dll!;E:\MainPro1\Unity\Library\ScriptAssemblies\Unity.Collections.dll!;E:\MainPro1\Unity\Library\ScriptAssemblies\Unity.Burst.dll!" -m -c -a "DCET.ObjectSystem" -e -ei -module -csc -define:UNITY_POST_PROCESSING_STACK_V2;ODIN_INSPECTOR;ODIN_INSPECTOR_3;XLUA;HOTFIX_ENABLE;ILRuntime
  at DCETEditor.LuaCompiler.Compile (System.String dllName, System.String dllDir, System.String outDirName, System.Collections.Generic.List`1[T] referencedLuaAssemblies, System.Boolean isModule) [0x00257] in E:\MainPro1\Unity\Assets\Editor\LuaCompiler\LuaCompiler.cs:116 
  at DCETEditor.GenCoreHotfix.CompileLua (System.String dllName, System.String dllDir, System.String outDirName, System.Collections.Generic.List`1[T] referencedLuaAssemblies, System.Boolean isModule) [0x00001] in E:\MainPro1\Unity\Assets\Editor\LuaCompiler\GenCoreHotfix.cs:123 
  at DCETEditor.GenCoreHotfix..cctor () [0x00102] in E:\MainPro1\Unity\Assets\Editor\LuaCompiler\GenCoreHotfix.cs:62 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])

**Comment by yanghuan** [comment]
```
namespace LuaTest {
  public struct FixVector3
  {
    public float x;
    public float y;
    public float z;
  }

  public struct float3
  {
    public float a;
    public float b;
    public float c;

    public float3(float a, float b, float c)
    {
      this.a = a;
      this.b = b;
      this.c = c;
    }

    public static implicit operator float3(FixVector3 value) {
      return new float3(value.x, value.y, value.z);
    }
  }

  public class Program {
    private static void Main(string[] args) {
    }
  }
}
```

我用此代码问发现此问题，可以更新最新的编译器测试下

**Comment by a772616239** [comment]
已经拉取最新工程，具体是是引用官方的 Unity.Mathematics库 或者是 Unity.Collections库

var value =new Unity.Mathematics.float3(1);

var coll=new Unity.Collections.NativeList<T>();
这两个库都会导致一直loading的问题

**Comment by yanghuan** [comment]
我测试了也是可以编译的，“一直loading的问题” 是运行时的问题的吗，那可能是这这个库的接口适配问题
