### ISSUE TITLE
Compiler has a bug

### ISSUE THREAD

**Issue by jackmoGo** [yanghuan/CSharp.lua#392]
Compile fail, CSharpLua.BugErrorException: SourceLocation(H:/...\B.cs@57:9)"data = new BackFlowTaskItemData
        {
            TData = info,
            CommonData =
            {
                iID = taskdata.iID,
                bAwardFlg = taskdata.bAwardFlg,
                iTargetProcess = taskdata.iTargetProcess,
                stReward = rewardList
            }
        };": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
 ---> System.Diagnostics.Contracts.ContractException
 ---> System.ApplicationException
   at CSharpLua.LuaSyntaxGenerator.<>c.<.cctor>b__27_0(Object _, ContractFailedEventArgs e) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 138
   at System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   at System.Diagnostics.Contracts.Contract.ReportFailure(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   at CSharpLua.LuaSyntaxNodeTransform.VisitInitializerExpression(InitializerExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 173
   at Microsoft.CodeAnalysis.CSharp.Syntax.InitializerExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1320
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1324
   at CSharpLua.LuaSyntaxNodeTransform.FillObjectInitializerExpression(LuaIdentifierNameSyntax temp, InitializerExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 110
   at CSharpLua.LuaSyntaxNodeTransform.GetObjectCreationInitializer(LuaExpressionSyntax creationExpression, BaseObjectCreationExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 58
   at CSharpLua.LuaSyntaxNodeTransform.VisitObjectCreationExpression(ObjectCreationExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 102
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1320
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1324
   at CSharpLua.LuaSyntaxNodeTransform.VisitExpression(ExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1288
   at CSharpLua.LuaSyntaxNodeTransform.BuildLuaAssignmentExpression(AssignmentExpressionSyntax node, ExpressionSyntax leftNode, ExpressionSyntax rightNode, SyntaxKind kind) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1826
   at CSharpLua.LuaSyntaxNodeTransform.InternalVisitAssignmentExpression(AssignmentExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1981
   at CSharpLua.LuaSyntaxNodeTransform.VisitAssignmentExpression(AssignmentExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2038
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1320
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1324
   at CSharpLua.LuaSyntaxNodeTransform.VisitExpressionStatement(ExpressionStatementSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1530
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1333
   --- End of inner exception stack trace ---
   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 219
   at CSharpLua.LuaSyntaxGenerator.Generate(String outFolder) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 246
   at CSharpLua.Compiler.Compile() in D:\Project\Person\CSharp.lua\CSharp.lua\Compiler.cs:line 123
   at CSharpLua.Program.Main(String[] args) in D:\Project\Person\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 90

**Comment by yanghuan** [comment]
麻烦提供一下可以复现的最小代码

**Comment by jackmoGo** [comment]
抱歉刚看到你的回复，看你已经修复了。
