### ISSUE TITLE
Compiler has a bug,

### ISSUE THREAD

**Issue by jackmoGo** [yanghuan/CSharp.lua#393]
Compile fail, CSharpLua.BugErrorException: SourceLocation(H:/Wepop_ILRuntime/...\P.cs@260:9)"TrackSelectSys.OpenPanel(parentUI, curTrackIdDel == null ? () => GetLastTrack(ModeSys.KeyWordModeType, entrance) : curTrackIdDel, menuType, OnChangeTrackClick);": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
 ---> System.Diagnostics.Contracts.ContractException
 ---> System.ApplicationException
   at CSharpLua.LuaSyntaxGenerator.<>c.<.cctor>b__27_0(Object _, ContractFailedEventArgs e) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 138
   at System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   at System.Diagnostics.Contracts.Contract.ReportFailure(ContractFailureKind failureKind, String userMessage, String conditionText, Exception innerException)
   at CSharpLua.LuaSyntaxNodeTransform.MayBeNull(ExpressionSyntax expression, ITypeSymbol type) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 669
   at CSharpLua.LuaSyntaxNodeTransform.MayBeNullOrFalse(ExpressionSyntax conditionalWhenTrue) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 719
   at CSharpLua.LuaSyntaxNodeTransform.VisitConditionalExpression(ConditionalExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 4837
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1320
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1324
   at CSharpLua.LuaSyntaxNodeTransform.FillInvocationArgument(List`1 arguments, ArgumentSyntax node, ImmutableArray`1 parameters, List`1 refOrOutArguments) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3208
   at CSharpLua.LuaSyntaxNodeTransform.BuildArgumentList(ISymbol symbol, ImmutableArray`1 parameters, BaseArgumentListSyntax node, List`1 refOrOutArguments) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3234
   at CSharpLua.LuaSyntaxNodeTransform.BuildInvocationArguments(IMethodSymbol symbol, InvocationExpressionSyntax node, List`1& refOrOutArguments) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2244
   at CSharpLua.LuaSyntaxNodeTransform.VisitInvocationExpression(InvocationExpressionSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2339
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1320
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1324
   at CSharpLua.LuaSyntaxNodeTransform.VisitExpressionStatement(ExpressionStatementSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1530
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1333
   --- End of inner exception stack trace ---
   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 219
   at CSharpLua.LuaSyntaxGenerator.Generate(String outFolder) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 246
   at CSharpLua.Compiler.Compile() in D:\Project\Person\CSharp.lua\CSharp.lua\Compiler.cs:line 123
   at CSharpLua.Program.Main(String[] args) in D:\Project\Person\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 90

**Comment by yanghuan** [comment]
麻烦提供一下可以复现的最小代码
