### ISSUE TITLE
Operator Overloading throws error even on ignore

### ISSUE THREAD

**Issue by Aeroverra** [yanghuan/CSharp.lua#416]
Class 
```cs
    public class Vector3 : Instance
    {
        /// <summary>
        /// @CSharpLua.Template = "Vector3.new({0},{1},{2})"
        /// </summary>
        /// <returns>Returns a new Vector3 from the given x, y, and z components.</returns>
        public extern Vector3(decimal x, decimal y, decimal z);

        /// <summary>
        /// The x-coordinate of the Vector3.
        /// </summary>
        public extern decimal X { get; set; }

        /// <summary>
        /// The y-coordinate of the Vector3.
        /// </summary>
        public extern decimal Y { get; set; }

        /// <summary>
        /// The z-coordinate of the Vector3.
        /// </summary>
        public extern decimal Z { get; set; }


        public static extern Vector3 operator +(Vector3 a, Vector3 b);

        public static extern Vector3 operator -(Vector3 a, Vector3 b);

        public static extern Vector3 operator *(Vector3 a, Vector3 b);

        public static extern Vector3 operator /(Vector3 a, Vector3 b);
    }
```
    
 Error
    
```cs
CSharpLua.BugErrorException: SourceLocation(../RobloxSharp\RobloxApis\Vector3.cs@9:5)"public class Vector3 : Instance
    {
        /// <summary>
        /// @CSharpLua.Template = "Vector3.new({0},{1},{2})"
        /// </summary>
        /// <returns>Returns a new Vector3 from the given x, y, and z components.</returns>
        public extern Vector3(decimal x, decimal y, decimal z);

        /// <summary>
        /// The x-coordinate of the Vector3.
        /// </summary>
        public extern decimal X { get; set; }

        /// <summary>
        /// The y-coordinate of the Vector3.
        /// </summary>
        public extern decimal Y { get; set; }

        /// <summary>
        /// The z-coordinate of the Vector3.
        /// </summary>
        public extern decimal Z { get; set; }


        public static extern Vector3 operator +(Vector3 a, Vector3 b);

        public static extern Vector3 operator -(Vector3 a, Vector3 b);

        public static extern Vector3 operator *(Vector3 a, Vector3 b);

        public static extern Vector3 operator /(Vector3 a, Vector3 b);
    }": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1320
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in D:\Project\Person\CSharp.lua\CSharp.lua\Utils.cs:line 1324
   at CSharpLua.LuaSyntaxNodeTransform.BuildOperatorMethodDeclaration(BaseMethodDeclarationSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 1184
   at CSharpLua.LuaSyntaxNodeTransform.VisitOperatorDeclaration(OperatorDeclarationSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 1203
   at Microsoft.CodeAnalysis.CSharp.Syntax.OperatorDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BuildTypeMembers(LuaTypeDeclarationSyntax typeDeclaration, TypeDeclarationSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 271
   at CSharpLua.LuaSyntaxNodeTransform.BuildTypeDeclaration(INamedTypeSymbol typeSymbol, TypeDeclarationSyntax node, LuaTypeDeclarationSyntax typeDeclaration) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 378
   at CSharpLua.LuaSyntaxNodeTransform.VisitTypeDeclaration(INamedTypeSymbol typeSymbol, TypeDeclarationSyntax node, LuaTypeDeclarationSyntax typeDeclaration) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 476
   at CSharpLua.LuaSyntaxNodeTransform.VisitClassDeclaration(ClassDeclarationSyntax node) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 543
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1333
   --- End of inner exception stack trace ---
   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 219
   at CSharpLua.LuaSyntaxGenerator.Generate(String outFolder) in D:\Project\Person\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 246
   at CSharpLua.Compiler.Compile() in D:\Project\Person\CSharp.lua\CSharp.lua\Compiler.cs:line 123
   at CSharpLua.Program.Main(String[] args) in D:\Project\Person\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 90
Press any key to continue . . .
C:\...\...\...\...\RobloxSharp\RobloxSharp\RobloxSharp.csproj(16,4): error MSB3073: The command "call build.cmd" exited with code -1.

 ```
    
    Adding the ignore attribute gives the same error

**Comment by Aeroverra** [comment]
Also amazing job on this. I was not expecting it to work as well as it does. I have implemented a few work arounds but I was not expecting it to be anywhere near as stable as it is.  Awesome work.

**Comment by Aeroverra** [comment]
Appears I have found a workaround for now by removing the extern modifier and specifying a template

```cs
  /// <summary>
        /// @CSharpLua.Template = "{0} + {1}"
        /// </summary>
        public static Vector3 operator +(Vector3 a, Vector3 b) => new Vector3(0, 0, 0);

        /// <summary>
        /// @CSharpLua.Template = "{0} - {1}"
        /// </summary>
        public static Vector3 operator -(Vector3 a, Vector3 b) => new Vector3(0, 0, 0);

        /// <summary>
        /// @CSharpLua.Template = "{0} * {1}"
        /// </summary>
        public static Vector3 operator *(Vector3 a, Vector3 b) => new Vector3(0, 0, 0);

        /// <summary>
        /// @CSharpLua.Template = "{0} / {1}"
        /// </summary>
        public static Vector3 operator /(Vector3 a, Vector3 b) => new Vector3(0, 0, 0);
```

**Comment by yanghuan** [comment]
i use the code, can not find error
```
public class Instance {

}

public class Vector3 : Instance {
  /// <summary>
  /// @CSharpLua.Template = "Vector3.new({0},{1},{2})"
  /// </summary>
  /// <returns>Returns a new Vector3 from the given x, y, and z components.</returns>
  public extern Vector3(decimal x, decimal y, decimal z);

  /// <summary>
  /// The x-coordinate of the Vector3.
  /// </summary>
  public extern decimal X { get; set; }

  /// <summary>
  /// The y-coordinate of the Vector3.
  /// </summary>
  public extern decimal Y { get; set; }

  /// <summary>
  /// The z-coordinate of the Vector3.
  /// </summary>
  public extern decimal Z { get; set; }


  public static extern Vector3 operator +(Vector3 a, Vector3 b);

  public static extern Vector3 operator -(Vector3 a, Vector3 b);

  public static extern Vector3 operator *(Vector3 a, Vector3 b);

  public static extern Vector3 operator /(Vector3 a, Vector3 b);
}

class Program {
  public static void Main(string[] args) {
    Vector3 a = default;
    Vector3 b = default;
    var c = a + b;
  }
}
```
