### ISSUE TITLE
stackalloc to span causes compiler error

### ISSUE THREAD

**Issue by joelverhagen** [yanghuan/CSharp.lua#451]
Minimal repro:
```csharp
Span<int> numbers = stackalloc int[4];
```

Seems like this could just compile to a normal heap allocated array in Lua.

Error:
```
CSharpLua.BugErrorException: SourceLocation(@6:7)"Span<int> numbers = stackalloc int[4];": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
 ---> System.InvalidCastException: Arg_InvalidCastException
   at CSharpLua.LuaSyntaxNodeTransform.VisitStackAllocArrayCreationExpression(StackAllocArrayCreationExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.StackAllocArrayCreationExpressionSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[LuaExpressionSyntax](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
   at CSharpLua.LuaSyntaxNodeTransform.VisitExpression(ExpressionSyntax node)
   at CSharpLua.LuaSyntaxNodeTransform.VisitEqualsValueClause(EqualsValueClauseSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.EqualsValueClauseSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[LuaEqualsValueClauseSyntax](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
   at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclarator(VariableDeclaratorSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[LuaVariableDeclaratorSyntax](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
   at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclaration(VariableDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclarationSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[LuaVariableDeclarationSyntax](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
   at CSharpLua.LuaSyntaxNodeTransform.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor)
   Exception_EndOfInnerExceptionStack
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor)
   at CSharpLua.LuaSyntaxNodeTransform.VisitTriviaAndNode(SyntaxNode rootNode, IEnumerable`1 nodes, Boolean isCheckBlank)+MoveNext()
   at CSharpLua.LuaAst.LuaSyntaxList`1[[CSharpLua.LuaAst.LuaStatementSyntax, CSharp.lua, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].AddRange(IEnumerable`1 collection)
   at CSharpLua.LuaSyntaxNodeTransform.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[LuaBlockSyntax](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform)
   at CSharpLua.LuaSyntaxNodeTransform.BuildMethodDeclaration(CSharpSyntaxNode node, SyntaxList`1 attributeLists, ParameterListSyntax parameterList, TypeParameterListSyntax typeParameterList, BlockSyntax body, ArrowExpressionClauseSyntax expressionBody)
   at CSharpLua.LuaSyntaxNodeTransform.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BuildTypeMembers(LuaTypeDeclarationSyntax typeDeclaration, TypeDeclarationSyntax node)
   at CSharpLua.LuaSyntaxNodeTransform.BuildTypeDeclaration(INamedTypeSymbol typeSymbol, TypeDeclarationSyntax node, LuaTypeDeclarationSyntax typeDeclaration)
   at CSharpLua.LuaSyntaxNodeTransform.VisitTypeDeclaration(INamedTypeSymbol typeSymbol, TypeDeclarationSyntax node, LuaTypeDeclarationSyntax typeDeclaration)
   at CSharpLua.LuaSyntaxNodeTransform.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor)
   at CSharpLua.LuaSyntaxNodeTransform.VisitTriviaAndNode(SyntaxNode rootNode, IEnumerable`1 nodes, Boolean isCheckBlank)+MoveNext()
   at CSharpLua.LuaAst.LuaSyntaxList`1[[CSharpLua.LuaAst.LuaStatementSyntax, CSharp.lua, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].AddRange(IEnumerable`1 collection)
   at CSharpLua.LuaAst.LuaWrapFunctionStatementSyntax.AddStatements(IEnumerable`1 statements)
   at CSharpLua.LuaSyntaxNodeTransform.BuildNamespaceDeclaration(BaseNamespaceDeclarationSyntax node)
   at CSharpLua.LuaSyntaxNodeTransform.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[LuaSyntaxNode](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor)
   at CSharpLua.LuaSyntaxNodeTransform.VisitTriviaAndNode(SyntaxNode rootNode, IEnumerable`1 nodes, Boolean isCheckBlank)+MoveNext()
   at CSharpLua.LuaSyntaxNodeTransform.VisitCompilationUnit(CompilationUnitSyntax node, Boolean isSingleFile)
   at CSharpLua.LuaSyntaxGenerator.CreateCompilationUnit(SyntaxTree syntaxTree, Boolean isSingleFile)
   at CSharpLua.LuaSyntaxGenerator.<>c__DisplayClass41_0.<Create>b__0(SyntaxTree i)
   at System.Linq.Enumerable.SelectArrayIterator`2[[Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[CSharpLua.LuaAst.LuaCompilationUnitSyntax, CSharp.lua, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Collections.Generic.List`1[[CSharpLua.LuaAst.LuaCompilationUnitSyntax, CSharp.lua, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[LuaCompilationUnitSyntax](IEnumerable`1 )
   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile)
   at CSharpLua.LuaSyntaxGenerator.GenerateSingle()
   at CSharpLua.Compiler.CompileSingleCode(String code, IEnumerable`1 libs, IEnumerable`1 metas)
   at CSharpLuaBlazor.Compiler.CompileInternal(String code)
```

**Comment by joelverhagen** [comment]
I've opened a PR to handle the stackalloc with a normal array (heap allocation) wrapped in a span.
