### ISSUE TITLE
Continue "find parent" fails to find parent for destructuring foreach

### ISSUE THREAD

**Issue by joelverhagen** [yanghuan/CSharp.lua#455]
Minimal C#:
```csharp
            var ts = new[] { (1, 2), (3, 4) };
            foreach (var (a, b) in ts)
            {
                if (a == 1)
                {
                    continue;
                }

                Console.WriteLine(a + b);
            }
```

Error:
```
CSharpLua.BugErrorException: SourceLocation(C:\Users\joelv\Desktop\LuaTest\LuaTest\Class1.cs@14:21)"continue;": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at CSharpLua.LuaSyntaxNodeTransform.<>c__DisplayClass219_0.<IsParentTryStatement>b__0(SyntaxNode i) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3956
   at CSharpLua.LuaSyntaxNodeTransform.FindParent(SyntaxNode node, Func`2 match) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 135
   at CSharpLua.LuaSyntaxNodeTransform.IsParentTryStatement(SyntaxNode node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3952
   at CSharpLua.LuaSyntaxNodeTransform.VisitContinueStatement(ContinueStatementSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 4871
   at Microsoft.CodeAnalysis.CSharp.Syntax.ContinueStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1351
   --- End of inner exception stack trace ---
   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 240
   at CSharpLua.LuaSyntaxGenerator.GenerateSingleFile(String outFile, String outFolder, IEnumerable`1 luaSystemLibs) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 286
   at CSharpLua.Compiler.Compile() in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Compiler.cs:line 129
   at CSharpLua.Program.Main(String[] args) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 90
```

**Comment by joelverhagen** [comment]
I've opened a PR to resolve this issue.
