### ISSUE TITLE
Struct in named tuple in anonymous method causes compiler to crash

### ISSUE THREAD

**Issue by joelverhagen** [yanghuan/CSharp.lua#457]
This does not happen with a `class`. This also happens with an anonymous type instead of a named tuple (although the error is different)

Minimal repro:
```csharp
namespace LuaTest
{
    public static class Class1
    {
        public static void Foo()
        {
            var d = new Location[1];
            // broken
            var y = d.Select(c => (A: 1, B: c));
            // broken
            var z = d.Select(c => new { A = 1, B = c });
        }
    }

    public struct Location
    {
        public Location(int x)
        {
            X = x;
        }

        public int X;
    }
}
```

Error:
```
B: c
CSharpLua.BugErrorException: SourceLocation(C:\Users\joelv\Desktop\LuaTest\LuaTest\Class1.cs@9:13)"var y = d.Select(c => (A: 1, B: c));": Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.First[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at CSharpLua.LuaSyntaxNodeTransform.GetParameterSymbol(IMethodSymbol symbol, ArgumentSyntax argument) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1248
   at CSharpLua.LuaSyntaxNodeTransform.CheckValueTypeClone(ITypeSymbol typeSymbol, IdentifierNameSyntax node, LuaExpressionSyntax& expression, Boolean isPropertyField) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1297
   at CSharpLua.LuaSyntaxNodeTransform.VisitIdentifierName(IdentifierNameSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3269
   at Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1486
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1490
   at CSharpLua.LuaSyntaxNodeTransform.<VisitTupleExpression>b__525_0(ArgumentSyntax i) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 1525
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at CSharpLua.LuaSyntaxNodeTransform.VisitTupleExpression(TupleExpressionSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 1525
   at Microsoft.CodeAnalysis.CSharp.Syntax.TupleExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1486
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1490
   at CSharpLua.LuaSyntaxNodeTransform.VisitLambdaExpression(IEnumerable`1 parameters, CSharpSyntaxNode body) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 515
   at CSharpLua.LuaSyntaxNodeTransform.VisitSimpleLambdaExpression(SimpleLambdaExpressionSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 542
   at Microsoft.CodeAnalysis.CSharp.Syntax.SimpleLambdaExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1486
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1490
   at CSharpLua.LuaSyntaxNodeTransform.VisitExpression(ExpressionSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1451
   at CSharpLua.LuaSyntaxNodeTransform.<>c__DisplayClass154_1.<FillCodeTemplateInvocationArguments>b__2() in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2250
   at CSharpLua.LuaSyntaxNodeTransform.InternalBuildCodeTemplateExpression(String codeTemplate, ExpressionSyntax targetExpression, IEnumerable`1 arguments, IList`1 typeArguments, LuaIdentifierNameSyntax memberBindingIdentifier) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 398
   at CSharpLua.LuaSyntaxNodeTransform.CheckCodeTemplateInvocationExpression(IMethodSymbol symbol, InvocationExpressionSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2294
   at CSharpLua.LuaSyntaxNodeTransform.VisitInvocationExpression(InvocationExpressionSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2410
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1486
   at CSharpLua.Utility.AcceptExpression(CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1490
   at CSharpLua.LuaSyntaxNodeTransform.VisitExpression(ExpressionSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Helper.cs:line 1451
   at CSharpLua.LuaSyntaxNodeTransform.VisitEqualsValueClause(EqualsValueClauseSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3574
   at Microsoft.CodeAnalysis.CSharp.Syntax.EqualsValueClauseSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1486
   at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclarator(VariableDeclaratorSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3568
   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1486
   at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclaration(VariableDeclarationSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3538
   at Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.Utility.Accept[T](CSharpSyntaxNode node, LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Utils.cs:line 1486
   at CSharpLua.LuaSyntaxNodeTransform.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 3468
   at Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transform) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1351
   --- End of inner exception stack trace ---
   at CSharpLua.LuaSyntaxGenerator.Create(Boolean isSingleFile) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 240
   at CSharpLua.LuaSyntaxGenerator.GenerateSingleFile(String outFile, String outFolder, IEnumerable`1 luaSystemLibs) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 286
   at CSharpLua.Compiler.Compile() in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua\Compiler.cs:line 129
   at CSharpLua.Program.Main(String[] args) in C:\z\Git\joelverhagen\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 90
```

**Comment by joelverhagen** [comment]
I was able to work around the problem by avoiding the anonymous type and named tuple. In this case, I can just use `KeyValuePair.Create(x, y)`

**Comment by joelverhagen** [comment]
@yanghuan there still seems to be a problem. This still repros:

```csharp

    public static class Class1
    {
        public static void Foo()
        {
            var aLocations = new Location[0];
            var bLocations = new Location[0];

            var lines = aLocations
                .SelectMany(al => bLocations.Where(bl => al.X == bl.X || al.Y == bl.Y).Select(bl => (A: al, B: bl)))
                .ToList();
        }
    }

    public struct Location
    {
        public Location(int x, int y)
        {
            X = x;
            Y = y;
        }

        public int X;
        public int Y;
    }
```
