### ISSUE TITLE
有个泛型的bug

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#68]
1>------ 已启动全部重新生成: 项目: LuaBridge, 配置: Debug Any CPU ------
1>  LuaBridge -> D:\NEW_Client\GameScript\LuaBridge\bin\Debug\LuaBridge.dll
2>------ 已启动全部重新生成: 项目: GameScript, 配置: Lua Any CPU ------
2>  GameScript -> D:\NEW_Client\GameScript\CSLua\bin\Debug\GameScript.dll
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\manifest.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\1_Framework\Databinding\BindableList.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\1_Framework\Databinding\BindableValue.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\1_Framework\Utility\Singleton.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\1_Framework\Utility\WindowResourceHelper.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\GameCore.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\DebugSystem\AliDebugSystem.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\HUDSystem\AliHUDModel.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\HUDSystem\AliHUDSystem.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\HUDSystem\AliHUDView.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\InputSystem\AliInputSystem.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\InputSystem\AliJoystickModel.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\InputSystem\AliJoyStickView.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\MVCSystem\AliModel.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\MVCSystem\AliSystem.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\MVCSystem\AliSystemMgr.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\MVCSystem\UI\AliUIMgr.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\MVCSystem\UI\AliUIView.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\Stage\AliGameStage.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\Stage\AliLoginStage.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\Stage\AliStage.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\Stage\AliStageMgr.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\UIViews\LoginView\LoginModel.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\UIViews\LoginView\LoginView.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\UIViews\SkillView\SkillModel.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\UIViews\SkillView\SkillView.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\WindowResources\HUDCanvasResource.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\WindowResources\JoystickUIResource.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\WindowResources\LoginUIResource.lua
2>  删除文件 - D:\NEW_Client\Assets\WorkDir\Resources\Lua\CompiledScripts\2_LogicSystem\WindowResources\SkillUIResource.lua
2>  start 2018/7/25 20:13:26
2>  System.Exception: Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue, SourceLocation(D:\NEW_Client\GameScript\/CSLua\2.LogicSystem\GameCore.cs@12:1)"namespace CSLua
2>  {
2>      public sealed class GameCore : Singleton<GameCore>
2>      {
2>          // 根对象
2>          public GameObject Root { get; private set; }
2>  
2>          public GameCore()
2>          {
2>              Button btn = null;
2>              var newButton = UnityEngine.Object.Instantiate(btn);
2>          }
2>          public void Start()
2>          {
2>              AliLogger.Log("CSLua GameMain Start");
2>              Root = AliLuaScriptMgr.Instance.gameObject;
2>              AliSystemMgr.Instance.Startup();
2>  
2>              //DatabindingTest();
2>          }
2>  
2>          // 数据绑定测试代码
2>          void DatabindingTest()
2>          {
2>              var mapId = AliProtoMgr.Instance.pvpMatchProto.RoomInfo.MapID;
2>              mapId.Value = 123;
2>              mapId.Set(234);
2>              var v = mapId.Value;
2>              AliLogger.Log("MapID {0} , {1}", v, mapId.Get());
2>  
2>              UnityEngine.Events.UnityAction<int, int> onChanged = (o, n) =>
2>              {
2>                  AliLogger.Log("onChanged MapID {0} , {1}", o, n);
2>              };
2>              mapId.AddListener(onChanged);
2>              mapId.Value = 1;
2>              mapId.Value = 2;
2>              mapId.Set(3);
2>              mapId.RemoveListener(onChanged);
2>              mapId.Value = 4;
2>              mapId.Value = 5;
2>              mapId.Set(6);
2>  
2>              mapId.AddListener(onChanged);
2>              mapId.Value = 7;
2>              mapId.Value = 8;
2>              mapId.Set(9);
2>              mapId.RemoveAllListeners();
2>              mapId.Value = 10;
2>              mapId.Value = 11;
2>              mapId.Set(12);
2>          }
2>  
2>          // 程序退出
2>          public void OnDestroy()
2>          {
2>              AliSystemMgr.Instance.Shutdown();
2>          }
2>  
2>          // lua逻辑主入口
2>          public static void Startup()
2>          {
2>              _instance = new GameCore();
2>              _instance.Start();
2>          }
2>          // lua逻辑退出
2>          public static void Destroy()
2>          {
2>              _instance.OnDestroy();
2>          }
2>      }
2>  }" ---> System.Exception: Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue, SourceLocation(D:\NEW_Client\GameScript\/CSLua\2.LogicSystem\GameCore.cs@14:5)"public sealed class GameCore : Singleton<GameCore>
2>      {
2>          // 根对象
2>          public GameObject Root { get; private set; }
2>  
2>          public GameCore()
2>          {
2>              Button btn = null;
2>              var newButton = UnityEngine.Object.Instantiate(btn);
2>          }
2>          public void Start()
2>          {
2>              AliLogger.Log("CSLua GameMain Start");
2>              Root = AliLuaScriptMgr.Instance.gameObject;
2>              AliSystemMgr.Instance.Startup();
2>  
2>              //DatabindingTest();
2>          }
2>  
2>          // 数据绑定测试代码
2>          void DatabindingTest()
2>          {
2>              var mapId = AliProtoMgr.Instance.pvpMatchProto.RoomInfo.MapID;
2>              mapId.Value = 123;
2>              mapId.Set(234);
2>              var v = mapId.Value;
2>              AliLogger.Log("MapID {0} , {1}", v, mapId.Get());
2>  
2>              UnityEngine.Events.UnityAction<int, int> onChanged = (o, n) =>
2>              {
2>                  AliLogger.Log("onChanged MapID {0} , {1}", o, n);
2>              };
2>              mapId.AddListener(onChanged);
2>              mapId.Value = 1;
2>              mapId.Value = 2;
2>              mapId.Set(3);
2>              mapId.RemoveListener(onChanged);
2>              mapId.Value = 4;
2>              mapId.Value = 5;
2>              mapId.Set(6);
2>  
2>              mapId.AddListener(onChanged);
2>              mapId.Value = 7;
2>              mapId.Value = 8;
2>              mapId.Set(9);
2>              mapId.RemoveAllListeners();
2>              mapId.Value = 10;
2>              mapId.Value = 11;
2>              mapId.Set(12);
2>          }
2>  
2>          // 程序退出
2>          public void OnDestroy()
2>          {
2>              AliSystemMgr.Instance.Shutdown();
2>          }
2>  
2>          // lua逻辑主入口
2>          public static void Startup()
2>          {
2>              _instance = new GameCore();
2>              _instance.Start();
2>          }
2>          // lua逻辑退出
2>          public static void Destroy()
2>          {
2>              _instance.OnDestroy();
2>          }
2>      }" ---> System.Exception: Compiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue, SourceLocation(D:\NEW_Client\GameScript\/CSLua\2.LogicSystem\GameCore.cs@22:13)"var newButton = UnityEngine.Object.Instantiate(btn);" ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PETypeParameterSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.
2>     at CSharpLua.XmlMetaProvider.MethodMetaInfo.GetTypeString(ITypeSymbol symbol) in D:\src\CSharp.lua\CSharp.lua\XmlMetaProvider.cs:line 179
2>     at CSharpLua.XmlMetaProvider.MethodMetaInfo.IsTypeMatch(ITypeSymbol symbol, String typeString) in D:\src\CSharp.lua\CSharp.lua\XmlMetaProvider.cs:line 199
2>     at CSharpLua.XmlMetaProvider.MethodMetaInfo.IsArgMatch(ITypeSymbol symbol, ArgumentModel parameterModel) in D:\src\CSharp.lua\CSharp.lua\XmlMetaProvider.cs:line 205
2>     at CSharpLua.XmlMetaProvider.MethodMetaInfo.IsMethodMatch(MethodModel model, IMethodSymbol symbol) in D:\src\CSharp.lua\CSharp.lua\XmlMetaProvider.cs:line 257
2>     at System.Collections.Generic.List`1.Find(Predicate`1 match)
2>     at CSharpLua.XmlMetaProvider.MethodMetaInfo.GetCodeTemplate(IMethodSymbol symbol) in D:\src\CSharp.lua\CSharp.lua\XmlMetaProvider.cs:line 288
2>     at CSharpLua.XmlMetaProvider.GetInternalMethodMetaInfo(IMethodSymbol symbol, MethodMetaType metaType) in D:\src\CSharp.lua\CSharp.lua\XmlMetaProvider.cs:line 560
2>     at CSharpLua.LuaSyntaxNodeTransform.CheckCodeTemplateInvocationExpression(IMethodSymbol symbol, InvocationExpressionSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1410
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitInvocationExpression(InvocationExpressionSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1500
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitEqualsValueClause(EqualsValueClauseSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2138
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclarator(VariableDeclaratorSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2130
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitVariableDeclaration(VariableDeclarationSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2110
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 2086
2>     at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 976
2>     --- End of inner exception stack trace ---
2>     at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 989
2>     at CSharpLua.LuaSyntaxNodeTransform.<VisitTriviaAndNode>d__80.MoveNext() in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1074
2>     at CSharpLua.LuaAst.LuaSyntaxList`1.AddRange(IEnumerable`1 collection) in D:\src\CSharp.lua\CSharp.lua\LuaAst\LuaSyntaxNode.cs:line 162
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitBlock(BlockSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1080
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitConstructorDeclaration(ConstructorDeclarationSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.Object.cs:line 337
2>     at CSharpLua.LuaSyntaxNodeTransform.BuildTypeMembers(LuaTypeDeclarationSyntax typeDeclaration, TypeDeclarationSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 212
2>     at CSharpLua.LuaSyntaxNodeTransform.BuildTypeDeclaration(INamedTypeSymbol typeSymbol, TypeDeclarationSyntax node, LuaTypeDeclarationSyntax typeDeclaration) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 279
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitTypeDeclaration(INamedTypeSymbol typeSymbol, TypeDeclarationSyntax node, LuaTypeDeclarationSyntax typeDeclaration) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 331
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitClassDeclaration(ClassDeclarationSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 411
2>     at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 976
2>     --- End of inner exception stack trace ---
2>     at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 989
2>     at CSharpLua.LuaSyntaxNodeTransform.<VisitTriviaAndNode>d__80.MoveNext() in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1074
2>     at CSharpLua.LuaAst.LuaSyntaxList`1.AddRange(IEnumerable`1 collection) in D:\src\CSharp.lua\CSharp.lua\LuaAst\LuaSyntaxNode.cs:line 162
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 208
2>     at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 976
2>     --- End of inner exception stack trace ---
2>     at CSharpLua.LuaSyntaxNodeTransform.BlockCommonNode.Visit(LuaSyntaxNodeTransform transfor) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 989
2>     at CSharpLua.LuaSyntaxNodeTransform.<VisitTriviaAndNode>d__80.MoveNext() in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 1074
2>     at CSharpLua.LuaSyntaxNodeTransform.VisitCompilationUnit(CompilationUnitSyntax node) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxNodeTransform.cs:line 187
2>     at CSharpLua.LuaSyntaxGenerator.Create() in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 128
2>     at CSharpLua.LuaSyntaxGenerator.Generate(String outFolder) in D:\src\CSharp.lua\CSharp.lua\LuaSyntaxGenerator.cs:line 148
2>     at CSharpLua.Program.Main(String[] args) in D:\src\CSharp.lua\CSharp.lua.Launcher\Program.cs:line 65
2>  已复制         1 个文件。
2>  Compile All GameScript to Lua Completed
========== 全部重新生成: 成功 2 个，失败 0 个，跳过 0 个 ==========

**Comment by mybios** [comment]
ompiler has a bug, thanks to commit issue at https://github.com/yanghuan/CSharp.lua/issue, SourceLocation(D:\NEW_Client\GameScript\/CSLua\2.LogicSystem\GameCore.cs@22:13)"var newButton = UnityEngine.Object.Instantiate(btn);" ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PETypeParameterSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.
